#ifndef GAME_CONSTANTS_HPP
#define GAME_CONSTANTS_HPP

#define BASE_TOWN_GOLD 10

// Power
#define PEASANT_POWER 1
#define TOWN_POWER 1
#define SOLDIER_POWER 2
#define FORTRESS_POWER 2
#define KNIGHT_POWER 3
#define HERO_POWER 4

// Cost
#define PEASANT_COST 10
#define SOLDIER_COST 20
#define KNIGHT_COST 40
#define HERO_COST 80

#define FORTRESS_COST 20

// Upkeep
#define PEASANT_UPKEEP 2
#define SOLDIER_UPKEEP 6
#define KNIGHT_UPKEEP 18
#define HERO_UPKEEP 54

#define FORTRESS_UPKEEP 2


#endif